version: '3'
services:
  web:
    build:
      context: .
    image: kanka
    container_name: kanka
    ports:
      - ${DOCKER_WEB_PORT}:80
    env_file:
      - .docker/web/variables.env
    environment:
      APP_DEBUG: ${APP_DEBUG}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL}
      DB_HOST: database
      DB_CONNECTION: mysql
      DB_DATABASE: kanka
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      REDIS_HOST: redis
    depends_on:
      - database
      - redis
